[project]
name = "zeroshotbalancer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "david-orjuela", email = "david1.orjuela@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "gymnasium[mujoco]>=1.3.0",
    "onnx>=1.23.0",
    "onnxruntime>=1.30.0",
    "pyserial>=3.5",
    "moviepy>=2.2.1",
    "scipy>=1.18.1",
    "stable-baselines3>=2.9.0",
    "tensorboard>=2.21.0",
    "torch>=2.14.0",
    "mujoco>=3.14.0"
]

[project.optional-dependencies]
tflite = [
    "tensorflow>=2.21.0",
]

